### ISSUE TITLE
BoundsError: attempt to access 1-element Vector{Int64} at index [2]

### ISSUE THREAD

**Issue by Zhang-jingxiang** [RainerHeintzmann/StructuredIlluminationMicroscopy.jl#2]
Hello!
I've been testing StructuredIlluminationMicroscopy.jl recently. Very excited that you have updated 3D-SIM! However, after updating the StructuredIlluminationMicroscopy.jl, there's a problem with this project. I ran the NL-SIM and failed with following error:
```
ERROR: BoundsError: attempt to access 1-element Vector{Int64} at index [2]
Stacktrace:
 [1] getindex
   @ .\essentials.jl:13 [inlined]
 [2] SIMPattern(h::Matrix{Float32}, sp::SIMParams, n::Int64, otf_num::Int64)
   @ StructuredIlluminationMicroscopy C:\Users\leilab\.julia\dev\StructuredIlluminationMicroscopy\src\sim_structures.jl:192
 [3] simulate_sim(obj::Matrix{Float32}, pp::PSFParams, sp::SIMParams, downsample_factor::Int64)
   @ StructuredIlluminationMicroscopy C:\Users\leilab\.julia\dev\StructuredIlluminationMicroscopy\src\simulate_sim.jl:117
 [4] macro expansion
   @ .\timing.jl:279 [inlined]
 [5] top-level scope
   @ c:\Users\leilab\.julia\environments\v1.10\rainer_st.jl:269
```
It seems to be a problem with the struct SIMParams related code. In the line 192 of the sim_structures.jl, if (otf_num == sp.otf_indices[i] && sp.peak_strengths[n, i] != 0.0). However, the sp.otf_indices is the 1-element Vector{Int64}. So the index goes out of bounds in the second loop. Is there something wrong with my operation?
Thank you!

**Comment by RainerHeintzmann** [comment]
Thanks for your comment. I cannot reproduce this. When I run the current code, this example (in the current version in the main branch) seems to run fine.
Maybe you are running your previous example code?

**Comment by Zhang-jingxiang** [comment]
Thanks! I have solved it!
